name: soccer_plus
description: Live soccer scores app with authentication and notifications
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.1
  firebase_auth_web: ^5.1.0  # Explicitly add this
  firebase_messaging: ^14.7.1
  cloud_firestore: ^4.8.3

  # State management
  provider: ^6.0.5

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Networking
  http: 1.4.0
  json_annotation: ^4.8.1

  # UI
  flutter_local_notifications: ^19.2.0
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.2
  intl: ^0.19.0

dev_dependencies:
  js: ^0.6.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  # Corrected localization configuration:
  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500